<a href="https://colab.research.google.com/github/haskinse/bee2041_empirical_project/blob/main/01_data_collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import drive # connect to google drive
drive.mount("/content/drive")

project_path = "/content/drive/MyDrive/bee2041_empirical_project" # define project path

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
from bs4 import BeautifulSoup  # parse HTML structure
from urllib.request import Request, urlopen # tools for sending a request to a website and retrieveing it's HTML content
import pandas as pd # library for data manipulation and tables
from io import StringIO # allows HTML strings to be treated as file objects for pandas so code still works in future versions

In [8]:
url = "https://en.wikipedia.org/wiki/Taylor_Swift_albums_discography"  # Wikipedia discography page

request = Request(url, headers = {"User-Agent": "Mozilla/5.0"}) # send request with browser-like header to avoid being blocked
page = urlopen(request)

html = page.read().decode("utf-8") # read and decode HTML

soup = BeautifulSoup(html, "html.parser") # parse the page using BeautifulSoup to target specific elements

wiki_tables = soup.find_all("table", class_ = "wikitable") # find all tables on the page that use Wikipedia's 'wikitable' format

for i, table in enumerate(wiki_tables): # look at table captions to identify which ones contain album data
  caption = table.find("caption")
  print(i, caption.get_text(strip = True) if caption else "No caption")

# pick relevant tables
studio_table_html = str(wiki_tables[0])
tv_table_html = str(wiki_tables[1])

# convert tables into pandas dataframes
wiki_studio_albums = pd.read_html(StringIO(studio_table_html))[0]
wiki_tv_albums = pd.read_html(StringIO(tv_table_html))[0]

0 List of studio albums, with selected chart positions, sales figures, and certifications
1 List of re-recorded albums, with selected details and chart positions
2 List of live albums with selected chart figures and notes
3 List of extended plays, with selected chart positions and sales figures
4 List of compilations
5 List of box sets

In [9]:
wiki_studio_albums.to_csv(f"{project_path}/data/raw/wiki_studio_albums.csv", index = False) # save raw data to drive

wiki_studio_albums.head() # show the first five rows

          Title                                      Album details  \
          Title                                      Album details
0  Taylor Swift  Released: October 24, 2006 Label: Big Machine ...
1      Fearless  Released: November 11, 2008 Label: Big Machine...
2     Speak Now  Released: October 25, 2010 Label: Big Machine ...
3           Red  Released: October 22, 2012 Label: Big Machine ...
4          1989  Released: October 27, 2014 Label: Big Machine ...

  Peak chart positions                                                    \
               US [19] AUS [6] CAN [8] DEN [16] IRE [17] NZ [9] NOR [18]
0                    5      33      14        —       59     38        —
1                    1       2       1       23        7      1        5
2                    1       1       1       26        6      1        4
3                    1       1       1        3        1      1        2
4                    1       1       1        2        1      1        1

                             \
  SPA [13] SWE [14] UK [10]
0        —        —      81
1       28       12       5
2       10       18       6
3        4        8       1
4        4       17       1

                                            Sales[a]  \
                                            Sales[a]
0                    US: 5,871,000[b] UK: 251,320[c]
1    US: 7,286,000[d] AUS: 500,000[e] UK: 718,518[c]
2                    US: 4,817,000[b] UK: 416,676[c]
3                    US: 4,582,000[b] UK: 874,532[c]
4  US: 6,472,000[b] CAN: 542,000[f] UK: 1,792,380[c]

                                      Certifications Unnamed: 14_level_0  \
                                      Certifications Unnamed: 14_level_1
0  RIAA: 8× Platinum[26] ARIA: 2× Platinum[27] BP...                 NaN
1  RIAA: 11× Platinum (Diamond)[33] ARIA: 8× Plat...                 NaN
2  RIAA: 6× Platinum[39] ARIA: 3× Platinum[27] BP...                 NaN
3  RIAA: 8× Platinum[43] ARIA: 5× Platinum[44] BP...                 NaN
4  RIAA: 14× Platinum (Diamond)[50] ARIA: 11× Pla...                 NaN

  Unnamed: 15_level_0 Unnamed: 16_level_0
  Unnamed: 15_level_1 Unnamed: 16_level_1
0                 NaN                 NaN
1                 NaN                 NaN
2                 NaN                 NaN
3                 NaN                 NaN
4                 NaN                 NaN

In [10]:
wiki_tv_albums.to_csv(f"{project_path}/data/raw/wiki_tv_albums.csv", index = False) # save raw data to drive

wiki_tv_albums.head() # show the first five rows

                          Title  \
                          Title
0   Fearless (Taylor's Version)
1        Red (Taylor's Version)
2  Speak Now (Taylor's Version)
3       1989 (Taylor's Version)

                                       Album details Peak chart positions  \
                                       Album details              US [19]
0  Released: April 9, 2021 Label: Republic Format...                    1
1  Released: November 12, 2021 Label: Republic Fo...                    1
2  Released: July 7, 2023 Label: Republic Formats...                    1
3  Released: October 27, 2023 Label: Republic For...                    1

                                                                               \
  AUS [6] CAN [8] DEN [16] IRE [17] NZ [9] NOR [18] SPA [13] SWE [14] UK [10]
0       1       1        8        1      1        2        3       17       1
1       1       1        3        1      1        1        3        8       1
2       1       1        6        1      1        2        1        1       1
3       1       1        1        1      1        1        1        1       1

                                       Sales[a]  \
                                       Sales[a]
0  US: 737,000[n] CAN: 18,000[o] UK: 217,947[c]
1  US: 950,000[n] CAN: 24,000[o] UK: 357,565[c]
2                 US: 908,000[p] UK: 209,302[c]
3               US: 2,389,000[b] UK: 390,226[c]

                                      Certifications
                                      Certifications
0  RIAA: 4× Platinum[103] ARIA: Platinum[83] BPI:...
1  RIAA: 6× Platinum[108] ARIA: 2× Platinum[58] B...
2  RIAA: 4× Platinum[114] ARIA: Platinum[83] BPI:...
3  RIAA: 4× Platinum[119] ARIA: 3× Platinum[58] B...

In [11]:
!pip install kaggle # install kaggle API package to allow data to be downloaded from Kaggle
import kagglehub # library to access and download kaggle datasets

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.2.25)

In [12]:
for i in range(2): # repeat download to avoid occasional Kaggle loading delays
    kagglehub.dataset_download("gabyxd/taylor-swift-song-information") # download the dataset from Kaggle

Using Colab cache for faster access to the 'taylor-swift-song-information' dataset.
Using Colab cache for faster access to the 'taylor-swift-song-information' dataset.

In [13]:
kaggle_data = pd.read_csv("/kaggle/input/taylor-swift-song-information/taylor_swift_songs.csv") # open the csv into a data frame

kaggle_data.to_csv(f"{project_path}/data/raw/kaggle_data.csv", index = False) # save raw data to drive

kaggle_data.head() # show the first five rows

,Unnamed: 0,track_name,album_name,key,mode,tempo,energy,danceability,duration_min,time_signature,valence,acousticness,instrumentalness,liveness,loudness,speechiness,release_date,album_id
0,0,Fortnight (feat. Post Malone),THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,B,Major,192.004,38.6,50.4,3.816083,4/4,28.1,50.20,0.00153,9.61,-10.976,3.08,2024-04-19,5H7ixXZfsNMGbIE5OBSpcb
1,1,The Tortured Poets Department,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,C,Major,110.259,42.8,60.4,4.884133,4/4,29.2,4.83,0.00000,12.60,-8.441,2.55,2024-04-19,5H7ixXZfsNMGbIE5OBSpcb
2,2,My Boy Only Breaks His Favorite Toys,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,C,Major,97.073,56.3,59.6,3.396683,4/4,48.1,13.70,0.00000,30.20,-7.362,2.69,2024-04-19,5H7ixXZfsNMGbIE5OBSpcb
3,3,Down Bad,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,B,Major,159.707,36.6,54.1,4.353800,4/4,16.8,56.00,0.00010,9.46,-10.412,7.48,2024-04-19,5H7ixXZfsNMGbIE5OBSpcb
4,4,"So Long, London",THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,A,Major,160.218,53.3,42.3,4.382917,4/4,24.8,73.00,0.26400,8.16,-11.388,32.20,2024-04-19,5H7ixXZfsNMGbIE5OBSpcb

In [14]:
!pip install spotipy # install Spotify API package to allow data to be downloaded from Spotify
import spotipy # library to access and download Spotify datasets
from spotipy.oauth2 import SpotifyClientCredentials # authentication method for accessing Spotify data without user login

Collecting spotipy
  Downloading spotipy-2.26.0-py3-none-any.whl.metadata (5.1 kB)
Collecting redis>=3.5.3 (from spotipy)
  Downloading redis-7.4.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests>=2.25.0 in /usr/local/lib/python3.12/dist-packages (from spotipy) (2.32.4)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from spotipy) (2.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25.0->spotipy) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25.0->spotipy) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.25.0->spotipy) (2026.2.25)
Downloading spotipy-2.26.0-py3-none-any.whl (31 kB)
Downloading redis-7.4.0-py3-none-any.whl (409 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.8/409.8 kB 6.2 MB/s eta 0:00:00
Installing collected packages: redis, spotipy
Successfully installed redis-7.4.0 spotipy-2.26.0

In [15]:
import os # used to access environment credentials (for spotify API)

In [16]:
os.environ["SPOTIPY_CLIENT_ID"] = "27f7d5d56da5437583e71c1290bc2114" # store client id for authentication
os.environ["SPOTIPY_CLIENT_SECRET"] = "f3f4f24ffd65477cb67f61c8baa36f5e" # store client secret for authentication

# credentials removed for security - see README

In [17]:
client_id = os.getenv("SPOTIFY_CLIENT_ID") # store client id for authentication
client_secret = os.getenv("SPOTIFY_CLIENT_SECRET") # store client secret for authentication

client_credentials_manager = SpotifyClientCredentials(client_id = client_id, client_secret = client_secret) # create an authentication manager

sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager) # create an API client for making requests

In [18]:
import time # used to delay code (handle API rate limits)

In [19]:
# search for taylor swift and pull out the first line
artist = sp.search(q = "artist:Taylor Swift", type = "artist", limit = 1)["artists"]["items"][0]

artist_id = artist["id"] # stores spotify artist id for API later
artist_name = artist["name"] # stores spotify artist name

all_albums = [] # make an empty list to store all album data
offset = 0 # set offset for paigination (spotify API can only return 10 results)

while True: # until stopped
  batch = sp.artist_albums(artist_id, album_type = "album", limit = 10, offset = offset)["items"] # retrieve a batch of albums

  if not batch: # if there are no more items in the batch
    break # break the loop

  else: # otherwise...
    all_albums.extend(batch) # add the new batch of albums to the albums list
    offset += 10 # move forward by ten albums (to get the next batch)
    time.sleep(0.5) # wait 0.5 seconds so the API isn't overwhelmed

rows = [] # make an empty list to store rows for the track data frame

for album in all_albums: # for each album in the list

  time.sleep(0.3)  # wait 0.3 seconds to avoid the rate limit

  tracks = sp.album_tracks(album["id"]) # retrieve track information for the current album

  for track in tracks["items"]: # for each track
    artist_list = [a["name"] for a in track["artists"]] # take the artists' names and store them in a list

    # add a dictionary to represent the row's data
    rows.append({"artist_name": ", ".join(artist_list), "album_name": album["name"], "release_date": album["release_date"], "track_name": track["name"], "track_number": track["track_number"], "explicit": track["explicit"]})

spotify_data = pd.DataFrame(rows) # read the list of rows into a data frame

spotify_data.to_csv(f"{project_path}/data/raw/spotify_data.csv", index = False) # save raw data to drive index = False) # store as a csv to avoid having to repeatedly use the spotify API

spotify_data.head() # show first five rows

,artist_name,album_name,release_date,track_name,track_number,explicit
0,Taylor Swift,The Life of a Showgirl + Acoustic Collection,2025-11-07,The Fate of Ophelia,1,False
1,Taylor Swift,The Life of a Showgirl + Acoustic Collection,2025-11-07,Elizabeth Taylor,2,False
2,Taylor Swift,The Life of a Showgirl + Acoustic Collection,2025-11-07,Opalite,3,False
3,Taylor Swift,The Life of a Showgirl + Acoustic Collection,2025-11-07,Father Figure,4,True
4,Taylor Swift,The Life of a Showgirl + Acoustic Collection,2025-11-07,Eldest Daughter,5,True

In [20]:
all_artists = [] # create an empty list to store artists

for artists in spotify_data["artist_name"]: # for each row's artist name column
  split_artists = artists.split(",") # split the artist names where there is a comma
  split_artists = [a.strip() for a in split_artists] # strip the whitespace
  all_artists.extend(split_artists) # add each split artist to the list

unique_artists = sorted(set(all_artists)) # sort the list and make it a set

In [21]:
import requests # used to send HTTP requests to APIs like Last.fm

In [22]:
def get_lastfm_stats(artist_name, api_key, base_url): # retrieve listener and playcount statistics for a given artist from the Last.fm API

  # define parameters for artist search
  search_params = {"method": "artist.search", "artist": artist_name, "api_key": api_key, "format": "json", "limit": 1}

  search_data = requests.get(base_url, params = search_params).json() # send request to Last.fm API and parse JSON response

  matches = search_data["results"]["artistmatches"]["artist"] # extract list of matching artists from search results

  matched_name = matches[0]["name"]  # pick the top match to ensure consistent artist identification

  # define parameters to retrieve detailed artist information
  info_params = {"method": "artist.getInfo", "artist": matched_name, "api_key": api_key, "format": "json", "autocorrect": 0}

  info_data = requests.get(base_url, params = info_params).json() # request artist information from Last.fm

  stats = info_data["artist"]["stats"] # extract listener and playcount statistics

  return stats["listeners"], stats["playcount"] # return metrics for analysis

In [23]:
os.environ["LASTFM_API_KEY"] = "7d1718434e0244f91c041df009bba61e" # store client id for authentication

# credentials removed for security - see README

In [24]:
api_key = os.getenv("LASTFM_API_KEY") # API key retrieved securely from environment variables
# credentials removed for security - see README

base_url = "https://ws.audioscrobbler.com/2.0/" # store the base url for Last.fm API

# manually specified stats for artists where API results are inconsistent or incorrect
manual_stats = {"Florence + The Machine": {"listeners": 3891116, "playcount": 280600000}}

rows = [] # create list to store rows of data for artist data frame

for artist_name in unique_artists: # for each artist

  if artist_name in manual_stats: # use manually defined values to override unreliable API results
    listeners = manual_stats[artist_name]["listeners"]
    playcount = manual_stats[artist_name]["playcount"]

  else: # retrieve listener and playcount data from Last.fm API
    listeners, playcount = get_lastfm_stats(artist_name, api_key, base_url)

  rows.append({"artist_name": artist_name, "listeners": listeners, "playcount": playcount}) # append artist statistics as a row in the dataset

  time.sleep(0.3) # pause between requests to avoid overwhelming API

In [25]:
lastfm_data = pd.DataFrame(rows) # create a data frame our of the rows

lastfm_data.to_csv(f"{project_path}/data/raw/lastfm_data.csv", index = False) # save raw data to drive

lastfm_data.head() # show first five rows

       artist_name listeners  playcount
0         Bon Iver   3549517  237795122
1     Brendon Urie     20540     303652
2  Chris Stapleton    872773   30213082
3   Colbie Caillat   2050556   36760665
4       Ed Sheeran   4190438  254653676