<a href="https://colab.research.google.com/github/haskinse/bee2041_empirical_project/blob/main/source_code/01_data_collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive # connect to google drive
drive.mount("/content/drive")

project_path = "/content/drive/MyDrive/bee2041_empirical_project" # define project path

Mounted at /content/drive

In [2]:
from urllib.request import Request, urlopen # tools for sending a request to a website and retrieveing it's HTML content
import pandas as pd # library for data manipulation and tables
from io import StringIO # allows HTML strings to be treated as file objects for pandas so code still works in future versions

In [3]:
url = "https://en.wikipedia.org/wiki/Taylor_Swift_albums_discography" # store the URL of wikipedia page

# create a request object with a browser-like header so that the request doesn't get blocked
request = Request(url, headers={"User-Agent": "Mozilla/5.0"})

page = urlopen(request) # open the web page
html_bytes = page.read() # read the HTML as bytes
html = html_bytes.decode("utf-8") # decode the bytes into a string

tables = pd.read_html(StringIO(html)) # extract the tables from the webpage into data frames

In [4]:
wiki_studio_albums = tables[1].copy() # create a copy of the second table on the website

wiki_studio_albums.to_csv(f"{project_path}/data/raw/wiki_studio_albums.csv", index = False) # save raw data to drive

wiki_studio_albums.head() # show the first five rows

          Title                                      Album details  \
          Title                                      Album details
0  Taylor Swift  Released: October 24, 2006 Label: Big Machine ...
1      Fearless  Released: November 11, 2008 Label: Big Machine...
2     Speak Now  Released: October 25, 2010 Label: Big Machine ...
3           Red  Released: October 22, 2012 Label: Big Machine ...
4          1989  Released: October 27, 2014 Label: Big Machine ...

  Peak chart positions                                                    \
               US [19] AUS [6] CAN [8] DEN [16] IRE [17] NZ [9] NOR [18]
0                    5      33      14        —       59     38        —
1                    1       2       1       23        7      1        5
2                    1       1       1       26        6      1        4
3                    1       1       1        3        1      1        2
4                    1       1       1        2        1      1        1

                             \
  SPA [13] SWE [14] UK [10]
0        —        —      81
1       28       12       5
2       10       18       6
3        4        8       1
4        4       17       1

                                            Sales[a]  \
                                            Sales[a]
0                    US: 5,871,000[b] UK: 251,320[c]
1    US: 7,286,000[d] AUS: 500,000[e] UK: 718,518[c]
2                    US: 4,817,000[b] UK: 416,676[c]
3                    US: 4,582,000[b] UK: 874,532[c]
4  US: 6,472,000[b] CAN: 542,000[f] UK: 1,792,380[c]

                                      Certifications Unnamed: 14_level_0  \
                                      Certifications Unnamed: 14_level_1
0  RIAA: 8× Platinum[26] ARIA: 2× Platinum[27] BP...                 NaN
1  RIAA: 11× Platinum (Diamond)[33] ARIA: 8× Plat...                 NaN
2  RIAA: 6× Platinum[39] ARIA: 3× Platinum[27] BP...                 NaN
3  RIAA: 8× Platinum[43] ARIA: 5× Platinum[44] BP...                 NaN
4  RIAA: 14× Platinum (Diamond)[50] ARIA: 11× Pla...                 NaN

  Unnamed: 15_level_0 Unnamed: 16_level_0
  Unnamed: 15_level_1 Unnamed: 16_level_1
0                 NaN                 NaN
1                 NaN                 NaN
2                 NaN                 NaN
3                 NaN                 NaN
4                 NaN                 NaN

In [5]:
wiki_tv_albums = tables[2].copy() # create a copy of the third table on the website

wiki_tv_albums.to_csv(f"{project_path}/data/raw/wiki_tv_albums.csv", index = False) # save raw data to drive

wiki_tv_albums.head() # show the first five rows

                          Title  \
                          Title
0   Fearless (Taylor's Version)
1        Red (Taylor's Version)
2  Speak Now (Taylor's Version)
3       1989 (Taylor's Version)

                                       Album details Peak chart positions  \
                                       Album details              US [19]
0  Released: April 9, 2021 Label: Republic Format...                    1
1  Released: November 12, 2021 Label: Republic Fo...                    1
2  Released: July 7, 2023 Label: Republic Formats...                    1
3  Released: October 27, 2023 Label: Republic For...                    1

                                                                               \
  AUS [6] CAN [8] DEN [16] IRE [17] NZ [9] NOR [18] SPA [13] SWE [14] UK [10]
0       1       1        8        1      1        2        3       17       1
1       1       1        3        1      1        1        3        8       1
2       1       1        6        1      1        2        1        1       1
3       1       1        1        1      1        1        1        1       1

                                       Sales[a]  \
                                       Sales[a]
0  US: 737,000[n] CAN: 18,000[o] UK: 217,947[c]
1  US: 950,000[n] CAN: 24,000[o] UK: 357,565[c]
2                 US: 908,000[p] UK: 209,302[c]
3               US: 2,389,000[b] UK: 390,226[c]

                                      Certifications
                                      Certifications
0  RIAA: 4× Platinum[103] ARIA: Platinum[83] BPI:...
1  RIAA: 6× Platinum[108] ARIA: 2× Platinum[58] B...
2  RIAA: 4× Platinum[114] ARIA: Platinum[83] BPI:...
3  RIAA: 4× Platinum[119] ARIA: 3× Platinum[58] B...

In [6]:
!pip install kaggle # install kaggle API package to allow data to be downloaded from Kaggle
import kagglehub # library to access and download kaggle datasets

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.2.25)

In [7]:
for i in range(2): # repeat download to avoid occasional Kaggle loading delays
    kagglehub.dataset_download("gabyxd/taylor-swift-song-information") # download the dataset from Kaggle

Downloading to /root/.cache/kagglehub/datasets/gabyxd/taylor-swift-song-information/3.archive...

100%|██████████| 12.1k/12.1k [00:00<00:00, 20.8MB/s]

Extracting files...

Using Colab cache for faster access to the 'taylor-swift-song-information' dataset.

In [8]:
kaggle_data = pd.read_csv("/kaggle/input/taylor-swift-song-information/taylor_swift_songs.csv") # open the csv into a data frame

kaggle_data.to_csv(f"{project_path}/data/raw/kaggle_data.csv", index = False) # save raw data to drive

kaggle_data.head() # show the first five rows

,Unnamed: 0,track_name,album_name,key,mode,tempo,energy,danceability,duration_min,time_signature,valence,acousticness,instrumentalness,liveness,loudness,speechiness,release_date,album_id
0,0,Fortnight (feat. Post Malone),THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,B,Major,192.004,38.6,50.4,3.816083,4/4,28.1,50.20,0.00153,9.61,-10.976,3.08,2024-04-19,5H7ixXZfsNMGbIE5OBSpcb
1,1,The Tortured Poets Department,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,C,Major,110.259,42.8,60.4,4.884133,4/4,29.2,4.83,0.00000,12.60,-8.441,2.55,2024-04-19,5H7ixXZfsNMGbIE5OBSpcb
2,2,My Boy Only Breaks His Favorite Toys,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,C,Major,97.073,56.3,59.6,3.396683,4/4,48.1,13.70,0.00000,30.20,-7.362,2.69,2024-04-19,5H7ixXZfsNMGbIE5OBSpcb
3,3,Down Bad,THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,B,Major,159.707,36.6,54.1,4.353800,4/4,16.8,56.00,0.00010,9.46,-10.412,7.48,2024-04-19,5H7ixXZfsNMGbIE5OBSpcb
4,4,"So Long, London",THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY,A,Major,160.218,53.3,42.3,4.382917,4/4,24.8,73.00,0.26400,8.16,-11.388,32.20,2024-04-19,5H7ixXZfsNMGbIE5OBSpcb